version: "3.9"

services:
  # MongoDB
  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: techchallenge
      #MONGO_INITDB_ROOT_USERNAME: mongo
      #MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27018:27017"
    networks:
      - fiap-network
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand('ping')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Spring Boot App
  app:
    build: .
    container_name: fiap-tech-challenge
    ports:
      - "8080:8080"
    networks:
      - fiap-network
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: mongodb://@mongodb:27018/techchallenge
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  fiap-network:
    driver: bridge

volumes:
  mongodb_data: